/**
 * [INPUT]: Host language tag
 * [OUTPUT]: Complete five-language interface vocabulary and label lookup
 * [POS]: GUI localization boundary; Base user content remains unchanged
 * [PROTOCOL]: Update this header when making changes, then check README.md.
 */
const messages = {
  en: {
    openData: "Open data",
    refresh: "Refresh",
    loading: "Loading…",
    error: "Could not load this App. Try again.",
    schema: "The Base columns have changed. Open data to review them.",
    search: "Search",
    allProjects: "All projects",
    allTime: "All time",
    allCategories: "All categories",
    empty: "No matching records",
    emptyHint: "Try changing the filters, or add records in Use chat.",
    previous: "Previous",
    next: "Next",
    clear: "Clear filters",
    unknown: "Unknown",
    count: "Records",
    uncategorized: "Uncategorized",
    title: "Expense Tracker",
    subtitle: "A clear view of everyday spending.",
    ledger: "Ledger",
    analysis: "Analysis",
    spent: "Spending",
    refunded: "Refunds",
    net: "Net spending",
    category: "Category",
    date: "Date",
    amount: "Amount",
    note: "Note",
    categories: "Spending by category",
    days: "Daily net spending",
    invalid:
      "Some rows have invalid dates or amounts and are excluded from totals.",
    food: "Food",
    transport: "Transport",
    shopping: "Shopping",
    housing: "Housing",
    health: "Health",
    entertainment: "Entertainment",
    other: "Other",
    month: "Month",
  },
  "zh-CN": {
    openData: "打开数据",
    refresh: "刷新",
    loading: "加载中…",
    error: "无法加载此应用，请重试。",
    schema: "数据列已变更，请打开数据检查。",
    search: "搜索",
    allProjects: "全部项目",
    allTime: "全部时间",
    allCategories: "全部分类",
    empty: "没有匹配的记录",
    emptyHint: "试试调整筛选，或在使用对话中添加记录。",
    previous: "上一页",
    next: "下一页",
    clear: "清除筛选",
    unknown: "未知",
    count: "记录数",
    uncategorized: "未分类",
    title: "记账本",
    subtitle: "每一笔开销，清楚看见。",
    ledger: "明细",
    analysis: "分析",
    spent: "支出",
    refunded: "退款",
    net: "净支出",
    category: "分类",
    date: "日期",
    amount: "金额",
    note: "备注",
    categories: "支出分类",
    days: "每日净支出",
    invalid: "部分记录的日期或金额无效，未计入统计。",
    food: "餐饮",
    transport: "交通",
    shopping: "购物",
    housing: "居住",
    health: "医疗",
    entertainment: "娱乐",
    other: "其他",
    month: "月份",
  },
  ja: {
    openData: "データを開く",
    refresh: "更新",
    loading: "読み込み中…",
    error: "読み込めませんでした。再試行してください。",
    schema: "列が変更されました。データを確認してください。",
    search: "検索",
    allProjects: "すべてのプロジェクト",
    allTime: "全期間",
    allCategories: "すべてのカテゴリ",
    empty: "一致する記録がありません",
    emptyHint: "条件を変更するか、チャットで記録を追加してください。",
    previous: "前へ",
    next: "次へ",
    clear: "条件を解除",
    unknown: "不明",
    count: "記録数",
    uncategorized: "未分類",
    title: "家計簿",
    subtitle: "日々の支出をひと目で。",
    ledger: "明細",
    analysis: "分析",
    spent: "支出",
    refunded: "返金",
    net: "純支出",
    category: "カテゴリ",
    date: "日付",
    amount: "金額",
    note: "メモ",
    categories: "カテゴリ別支出",
    days: "日別純支出",
    invalid: "日付や金額が無効な記録は集計から除外されています。",
    food: "食事",
    transport: "交通",
    shopping: "買い物",
    housing: "住居",
    health: "医療",
    entertainment: "娯楽",
    other: "その他",
    month: "月",
  },
  fr: {
    openData: "Ouvrir les données",
    refresh: "Actualiser",
    loading: "Chargement…",
    error: "Chargement impossible. Réessayez.",
    schema: "Les colonnes ont changé. Vérifiez les données.",
    search: "Rechercher",
    allProjects: "Tous les projets",
    allTime: "Toute la période",
    allCategories: "Toutes les catégories",
    empty: "Aucun résultat",
    emptyHint: "Modifiez les filtres ou ajoutez des données dans le chat.",
    previous: "Précédent",
    next: "Suivant",
    clear: "Effacer les filtres",
    unknown: "Inconnu",
    count: "Écritures",
    uncategorized: "Sans catégorie",
    title: "Suivi des dépenses",
    subtitle: "Vos dépenses quotidiennes en un coup d’œil.",
    ledger: "Écritures",
    analysis: "Analyse",
    spent: "Dépenses",
    refunded: "Remboursements",
    net: "Dépenses nettes",
    category: "Catégorie",
    date: "Date",
    amount: "Montant",
    note: "Note",
    categories: "Dépenses par catégorie",
    days: "Dépenses nettes par jour",
    invalid: "Certaines dates ou sommes sont invalides et exclues des totaux.",
    food: "Alimentation",
    transport: "Transport",
    shopping: "Achats",
    housing: "Logement",
    health: "Santé",
    entertainment: "Loisirs",
    other: "Autre",
    month: "Mois",
  },
  es: {
    openData: "Abrir datos",
    refresh: "Actualizar",
    loading: "Cargando…",
    error: "No se pudo cargar. Inténtalo de nuevo.",
    schema: "Las columnas cambiaron. Revisa los datos.",
    search: "Buscar",
    allProjects: "Todos los proyectos",
    allTime: "Todo el período",
    allCategories: "Todas las categorías",
    empty: "Sin resultados",
    emptyHint: "Cambia los filtros o añade registros en el chat.",
    previous: "Anterior",
    next: "Siguiente",
    clear: "Borrar filtros",
    unknown: "Desconocido",
    count: "Registros",
    uncategorized: "Sin categoría",
    title: "Registro de gastos",
    subtitle: "Tus gastos diarios, de un vistazo.",
    ledger: "Movimientos",
    analysis: "Análisis",
    spent: "Gastos",
    refunded: "Reembolsos",
    net: "Gasto neto",
    category: "Categoría",
    date: "Fecha",
    amount: "Importe",
    note: "Nota",
    categories: "Gastos por categoría",
    days: "Gasto neto diario",
    invalid: "Se excluyen de los totales las fechas o importes no válidos.",
    food: "Comida",
    transport: "Transporte",
    shopping: "Compras",
    housing: "Vivienda",
    health: "Salud",
    entertainment: "Ocio",
    other: "Otros",
    month: "Mes",
  },
};
export type Copy = typeof messages.en;
export function getCopy(language: string): Copy {
  const locale = /^zh/i.test(language)
    ? "zh-CN"
    : /^(ja|fr|es)(?:-|$)/i.test(language)
      ? language.slice(0, 2).toLowerCase()
      : "en";
  return messages[locale as keyof typeof messages] ?? messages.en;
}
export function label(copy: Copy, key: string) {
  return copy[key as keyof Copy] ?? key;
}
